# Análisis de Datos Poblacionales en la Ciudad de Boston

Se nos pide realizar un análisis de datos sobre los precios del mercado de viviendas en la ciudad de Boston `median_value`, Así como datos adicionales sobre la ubicación de al vivienda y otros datos sociodemográficos.

## Load Data and Libraries

Cargamos la data .csv y las librerías necesarias para el análisis, visualización de datos para cumplir con los objetivos solicitados en el primer entregable de MD004.

In [1]:
# Import libraries
import numpy as np
import pandas as pd

# Data visualizacion
import matplotlib.pyplot as plt
import seaborn as sns

# Set style
sns.set_style('darkgrid')
# set options to display all columns
pd.set_option('display.max_columns', None)

In [2]:
# Load data
data = pd.read_csv('../data/20230119_DatosBoston.csv', sep = ';')

## 1. Análisis exploratorio de los datos.

El proveedor de los datos suministra una descripción de cada una de las valiables del dataset.

* `crime_index`: Índice de criminalidad de la zona
* `urban_ratio`: Ratio de zona urbana residencial sobre el total
* `industry_ratio`: Ratio de industria de la zona
* `c_river_variable`: 1 si la zona colinda con un río y 0 si no
* `nox_concentration`: Concentración de óxido nitroso en la zona
* `rooms_per_dwelling`: Número de habitaciones medio por vivienda
* `dwelling_age`: “Edad” media de la vivienda
* `dwelling_dist`: Distancia media ponderada con los centros urbanos de la ciudad
* `highway_index`: Índice de accesibilidad sobre autopistas cercanas
* `tax_ratio`: Índice de tasas por cada 10000usd
* `teacher_ratio`: Ratio de alumno por profesor
* `racial_index`: Índice de proporción de población no caucásica
* `lower_status`: Porcentaje de población de “clase-baja”
* `median_value`: Valor medio de precio de la vivienda (En 1000USD)

Vamos a realizar un analisis exploratorio de los datos, para entender la distribución de cada una de las variables, y posterior realizar un análisis de correlación entre las variables para entender la relación entre ellas y el precio de la vivienda `median_value`.

### 1.1 SHAPE, INFO y Estadísticos descriptivos

Iniciemos con una revisión del tamaño de la data y veamos los estadísticos descriptivos principales.

In [5]:
# Show Shape and INFO
print('Shape of the data (rows, columns): ', data.shape)
print('\nInfo of the data: ')
data.info()

Shape of the data (rows, columns):  (506, 14)

Info of the data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   crime_index         506 non-null    float64
 1   urban_ratio         506 non-null    float64
 2   industry_ratio      506 non-null    float64
 3   c_river_variable    506 non-null    int64
 4   nox_concentration   506 non-null    float64
 5   rooms_per_dwelling  506 non-null    float64
 6   dwelling_age        506 non-null    float64
 7   dwelling_dist       506 non-null    float64
 8   highway_index       506 non-null    int64
 9   tax_ratio           506 non-null    int64
 10  teacher_ratio       506 non-null    float64
 11  racial_index        506 non-null    float64
 12  lower_status        506 non-null    float64
 13  median_value        506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

No poseemos variables categóricas en el dataset, por lo tanto no es necesario hacer exploraciones categóricas. Procedemos entonces a revisar los estadísticos descriptivos de las variables numéricas.

In [7]:
# Show Head and Tail data
print('Head of the data: ')
display(data.head(10))
print('\nTail of the data: ')
display(data.tail(10))

Head of the data:

,crime_index,urban_ratio,industry_ratio,c_river_variable,nox_concentration,rooms_per_dwelling,dwelling_age,dwelling_dist,highway_index,tax_ratio,teacher_ratio,racial_index,lower_status,median_value
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.090,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,49.671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,49.671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,60.622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,60.622,3,222,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,60.622,3,222,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,55.605,5,311,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,59.505,5,311,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,60.821,5,311,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,65.921,5,311,15.2,386.71,17.10,18.9

Tail of the data:

,crime_index,urban_ratio,industry_ratio,c_river_variable,nox_concentration,rooms_per_dwelling,dwelling_age,dwelling_dist,highway_index,tax_ratio,teacher_ratio,racial_index,lower_status,median_value
496,0.28960,0.0,9.69,0,0.585,5.390,72.9,27.986,6,391,19.2,396.90,21.14,19.7
497,0.26838,0.0,9.69,0,0.585,5.794,70.6,28.927,6,391,19.2,396.90,14.10,18.3
498,0.23912,0.0,9.69,0,0.585,6.019,65.3,24.091,6,391,19.2,396.90,12.92,21.2
499,0.17783,0.0,9.69,0,0.585,5.569,73.5,23.999,6,391,19.2,395.77,15.10,17.5
500,0.22438,0.0,9.69,0,0.585,6.027,79.7,24.982,6,391,19.2,396.90,14.33,16.8
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,24.786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,22.875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,21.675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,23.889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.505,1,273,21.0,396.90,7.88,11.9

In [6]:
# Description Data
data.describe()

,crime_index,urban_ratio,industry_ratio,c_river_variable,nox_concentration,rooms_per_dwelling,dwelling_age,dwelling_dist,highway_index,tax_ratio,teacher_ratio,racial_index,lower_status,median_value
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,131.695678,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,33.836573,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,246.395746,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,22.912317,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.137000,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,17.930000,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,27.533000,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,143.337000,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,47.648250,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,996.654000,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,121.265000,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000