# S6T3 Data Cleaning Accomodation Nights Booked

Después de ver los métodos de limpieza de datos, preprocesamiento y demás. Ahora se nos pide a través del fichero de `./data/accomodation_nigths_boocked.csv` responder a una serie de preguntas clave que solo son posible si se ha realizado el proceso de limpieza de datos. El dataset contiene las siguientes features:

* `id`: identificador único de cada reserva
* `no_of_adults`: número de adultos
* `no_of_children`: número de niños
* `no_of_weekend_nights`: número de noches de fin de semana (sábado o domingo) que el huésped se alojó o reservó para alojarse en el hotel
* `no_of_week_nights`: número de noches entre semana (de lunes a viernes) que el huésped se alojó o reservó para alojarse en el hotel
* `type_of_meal_plan`: tipo de plan de comidas reservado por el cliente
* `required_car_parking_space`: ¿El cliente requiere un espacio de estacionamiento para el auto? (0 - No, 1 - Sí)
* `room_type_reserved`: tipo de habitación reservada por el cliente. Los valores están cifrados (codificados) por INN Hotels
* `lead_time`: número de días entre la fecha de reserva y la fecha de llegada
* `arrival_year`: año de la fecha de llegada
* `arrival_month`: mes de la fecha de llegada
* `arrival_date`: fecha de llegada
* `market_segment_type`: designación del segmento de mercado
* `repeated_guest`: ¿Es el cliente un huésped repetido? (0 - No, 1 - Sí)
* `no_of_previous_cancellations`: número de reservas anteriores que fueron canceladas por el cliente antes de la reserva actual
* `no_of_previous_bookings_not_canceled`: número de reservas anteriores no canceladas por el cliente antes de la reserva actual
* `avg_price_per_room`: precio promedio por día de la reserva; los precios de las habitaciones son dinámicos (en euros)
* `no_of_special_requests`: número total de solicitudes especiales realizadas por el cliente (por ejemplo, piso alto, vista desde la habitación, etc.)
booking_status (0 o 1)

Las preguntas clave a responder son:

1. ¿En qué trimestre se producen un menor número de cancelaciones para las reservas de hotel tipo ciudad?
2. ¿Qué relación existe entre la variable lead_time y las cancelaciones de las reservas?
3. ¿Qué relación existe entre la variable deposit_type y la cancelación de la reserva?
4. ¿Qué mes del año tiene un precio medio de reserva mayor para las reservas de hotel tipo resort?

## Import Libraries and Load Data

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
sns.set_style('whitegrid')

In [5]:
# Load data
df = pd.read_csv('../data/accomodation_nights_booked.csv')
df.sample(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
27259,Resort Hotel,0,72,2016,August,34,16,2,6,2,2.0,0,HB,ESP,Direct,Direct,0,0,0,C,C,3,No Deposit,250.0,NaN,0,Transient,261.25,0,2,Check-Out,2016-08-24
65792,City Hotel,1,157,2017,April,14,8,2,2,2,0.0,0,BB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,117.00,0,0,Canceled,2017-02-17
14912,Resort Hotel,1,57,2015,July,27,2,0,3,1,0.0,0,BB,PRT,Direct,Direct,1,1,3,A,A,0,No Deposit,NaN,NaN,0,Transient,63.00,0,0,Canceled,2015-06-14
54902,City Hotel,0,214,2016,July,31,29,2,2,2,0.0,0,SC,BEL,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,9.0,NaN,0,Transient-Party,80.75,0,1,Check-Out,2016-08-02
10830,Resort Hotel,1,53,2017,April,14,7,2,5,2,1.0,0,BB,FRA,Direct,Direct,0,0,0,G,G,0,No Deposit,250.0,NaN,0,Transient,187.71,0,0,Canceled,2017-02-14
110170,City Hotel,0,133,2017,April,16,19,0,4,2,0.0,0,BB,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,390.0,NaN,0,Transient-Party,124.00,0,0,Check-Out,2017-04-23
95267,City Hotel,0,9,2016,August,34,14,2,1,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,NaN,0,Transient,116.27,0,1,Check-Out,2016-08-17
66349,City Hotel,1,141,2017,April,16,17,1,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,130.50,0,0,Canceled,2016-12-13
15909,Resort Hotel,0,93,2015,August,32,2,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,134.00,0,3,Check-Out,2015-08-07
11385,Resort Hotel,1,214,2017,May,18,5,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,54.00,0,0,Canceled,2016-10-04

## Data Cleaning

Veamos ahora como esta puesta la data y que valores nulos y el estado de la data en tipos.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

Por lo que vemos, los valores nulos estan presentes en `childre`, `country`, `agent` y `company`. Para responder las preguntas, incialmente no parece ser necesario tratarlos.

Para responder a la primera pregunta, debemos procesar para encontrar el numero de trimestres mediante la columna de `reservation_status_date`. Por tanto, vamos a crear una nueva columna al respecto.

In [8]:
# Get quarter number throught `reservation_satus_date``
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

df['reservation_status_quarter'] = 'Q' + df.reservation_status_date.dt.quarter.astype(str)
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,reservation_status_quarter
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,Q3
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,Q3
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,Q3
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,Q3
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03,Q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06,Q3
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07,Q3
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07,Q3
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07,Q3
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07,Q3